apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-grafana-dashboard
  labels:
    grafana_dashboard: "1"
  annotations:
    grafana_folder: "{{ $.Values.folder }}"
data:
  "{{ $.Release.Name }}.json": |
{{ .Files.Get "dashboards/dashboard.json" | indent 4 }}